#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034,SC2154

START=99
USE_PROCD=1

script=$(readlink "$initscript")
NAME="$(basename ${script:-$initscript})"
config_load "$NAME"

start_service() {
    /usr/bin/harpynet prepare || return 1

    procd_open_instance
    procd_set_param command /usr/bin/mihomo -d /tmp/mihomo
    procd_set_param respawn 3600 5 5
    procd_set_param file /tmp/mihomo/config.yaml
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    /usr/bin/harpynet cleanup
}

reload_service() {
    stop
    start
}

service_triggers() {
    config_get enable_badwan_interface_monitoring "settings" "enable_badwan_interface_monitoring"
    config_get badwan_monitored_interfaces "settings" "badwan_monitored_interfaces"
    config_get badwan_reload_delay "settings" "badwan_reload_delay" "2000"

    PROCD_RELOAD_DELAY=$badwan_reload_delay

    procd_open_trigger
    if [ "$enable_badwan_interface_monitoring" = "1" ]; then
        for iface in $badwan_monitored_interfaces; do
            procd_add_interface_trigger "interface.*.up" "$iface" /etc/init.d/harpynet reload
        done
    fi
    procd_close_trigger
}
